#!/bin/sh

message=$1 # First parameter will be the commit message
currentBranch=$(git symbolic-ref --short -q HEAD) # Getting the current branch

if [ ! -z "$1" ] # checking if the commit message is present. If not then aborting.
then
    echo "Message $message, Branch $currentBranch"
else
    echo "Commit origin $currentBranch"
fi